### ISSUE TITLE
As a potential contributor, i'd like to know the deadline for contributions, so i can determine if my team and i can meet the timeline

### ISSUE THREAD

**Issue by aassoiants** [ZapriteApp/phoenix-server-wallet-bounty#2]

**Comment by john-zaprite** [comment]
Apologies for the very long delay. I wasn't getting notifications for some reason. There was no set deadline, but we have awarded the bounty to someone. If that changes I'll reopen it.

**Comment by aassoiants** [comment]
Awesome! Big congrats!
